### ISSUE TITLE
Example ALLOWED_DOMAINS in README

### ISSUE THREAD

**Issue by serathius** [Valian/docker-nginx-auto-ssl#1]
I would propose better domain regexp as one presented in README `.*example.com` could match `any-example.com` or suffix that really does not fit domain based hierarchy.
Usually people would use exact domains and subdomains, or wildcard.
domain `ALLOWED_DOMAINS=example.com`
subdomains `ALLOWED_DOMAINS=(www|api).example.com`
wildcard `ALLOWED_DOMAINS=([a-z]+.)?example.com`
Also it would be good to explain how lua handles unicode strings. From http://lua-users.org/wiki/LuaUnicode you can get that it would be better to replace `.*` with `[a-z]+`

**Comment by Valian** [comment]
Thanks @serathius, it's fixed
