### ISSUE TITLE
PR for Redis support?

### ISSUE THREAD

**Issue by jede** [Valian/docker-nginx-auto-ssl#15]
Hi,

Thanks for a great Docker image! 🐳

I noticed that the https://github.com/GUI/lua-resty-auto-ssl library has built in Redis support, we are running this image on AWS and are looking into storing the certificates in an Elasticache Redis. We could of course make our own image and override the configs, however I thought I would ask if you would be interested in a PR adding it to the parameters?

I'm thinking something like this:

```
docker run -d \
  --name nginx-auto-ssl \
  --restart on-failure \
  --network host \
  -e ALLOWED_DOMAINS="$DOMAIN" \
  -e SITES="$DOMAIN=$APP_ADDRESS" \
  -e STORAGE_ADAPTER="redis" \
  -e REDIS_HOST="127.0.0.1" \
  -e REDIS_PORT="6379" \
  -v ssl-data:/etc/resty-auto-ssl \
  valian/docker-nginx-auto-ssl
```

Best regards,
Johannes

**Comment by jede** [comment]
Hi! Great, I'll look into it and see what I come up with :)

**Comment by devpascoe** [comment]
FYI on this. I have it working using an override of resty-http.conf
Made my own image using Dockerfile
FROM valian/docker-nginx-auto-ssl
COPY resty-http.conf /usr/local/openresty/nginx/conf/resty-http.conf

Within my version of resty-http.conf its identical to the one found in this repo's snippets folder but just added  after the allow_domain callback
  auto_ssl:set("storage_adapter", "resty.auto-ssl.storage_adapters.redis")
  auto_ssl:set("redis", {
    host = "myredishost",
    db = 15
  })

Awesome repo, thanks.
