### ISSUE TITLE
Cannot Find errors, no ssl certificate issued

### ISSUE THREAD

**Issue by appunni-dishq** [Valian/docker-nginx-auto-ssl#19]
```
#!/usr/bin/env bash
ALLOWED_DOMAINS=tel.app.domain.com,api.app.domain.com,app.domain.com
SITES="tel.app.domain.com=http://127.0.0.1:8090;api.app.domain.com=http://127.0.0.1:8080;app.domain.com=http://127.0.0.1:8000"
LETSENCRYPT_URL=https://acme-v01.api.letsencrypt.org/directory


docker run -d --name nginx-auto-ssl --restart on-failure \
--net=host \
-e ALLOWED_DOMAINS=${ALLOWED_DOMAINS} \
-e SITES=${SITES} \
-e FORCE_HTTPS=true \
-e LETSENCRYPT_URL=$LETSENCRYPT_URL \
valian/docker-nginx-auto-ssl
```

I am not getting any errors  on `docker logs  nginx-auto-ssl` but, seems like no ssl certificate is being issued. Can you help me

**Comment by Valian** [comment]
@appunni-dishq everything seems to be set up correctly. How exactly are you trying to reach this website? Are you sure proper host header is there?

**Comment by appunni-dishq** [comment]
I found the issue, it was the configuration. Need better documentation on
ALLOWED DOMAINS it accepts a regex not comma separated values .

**Comment by Valian** [comment]
I have a feeling it's documented properly:

> Regex pattern of allowed domains. Internally, we're using ngx.re.match. By default we accept all domains

If you think it's not enough, please drop a suggestion. For now I'm closing this issue, glad it worked for you.
