### ISSUE TITLE
Duplicated location in case of SSL

### ISSUE THREAD

**Issue by MSusik** [Valian/docker-nginx-auto-ssl#2]
The error I encounter while using this repo with SSL turned on:

```2018/05/28 09:19:19 [emerg] 1#1: duplicate location "/" in /usr/local/openresty/nginx/conf/force-https.conf:1
nginx: [emerg] duplicate location "/" in /usr/local/openresty/nginx/conf/force-https.conf:1
```

When `force-https.conf` file is cleared, everything works fine (except for the removed redirect).

**Comment by Valian** [comment]
Please share your configuration or at least steps to reproduce. I bet that you're including location `/` in an `HTTP` server (exactly what `force-https.conf` does). That's probably error in your own config, not this repository.

To solve it, you can try to set env variable  `FORCE_HTTPS=false`, but then you'll have to redirect from HTTP to HTTPS on your own.

**Comment by Valian** [comment]
I found the issue, it happened when you was starting the same container multiple times.
