### ISSUE TITLE
Certificate Validity &  Security Pinning 

### ISSUE THREAD

**Issue by AmitDJagtap** [Valian/docker-nginx-auto-ssl#21]
This is more of a question rather than an issue If the certificate is used in my app and cert expires. How will it affect the app [ app requests won't work], But if docker-nginx-auto-ssl to renew the certificate or generate a new one, which will not work with old app build? 

How does this work?

**Comment by Valian** [comment]
This image makes use of a great module https://github.com/GUI/lua-resty-auto-ssl. I believe you should be able to find all the details in their readme file. In short, it generates certificates on-the-fly whenever valid certificate can't be found or is close to expiring, you shouldn't need to provide your own certificates at all.
