### ISSUE TITLE
How to save issued certificates for prevent additional request on any new container start?

### ISSUE THREAD

**Issue by indapublic** [Valian/docker-nginx-auto-ssl#25]

**Comment by Valian** [comment]
@indapublic All examples in README should keep their certificates between container restarts. You need to keep content of `/etc/resty-auto-ssl` in a volume.

**Comment by indapublic** [comment]
@Valian Thanks for your reply.

Yes, but after several container restarts, I get a message that the number of requests for my domain is exceeded, from which I can conclude that regeneration is occurring every start.

**Comment by Valian** [comment]
@indapublic Please post your exact configuration - how you are starting this container, together with logs indicating an error. I'll reopen the issue if it will be the fault of the image.
