### ISSUE TITLE
Option to force https redirect as a temporary redirect

### ISSUE THREAD

**Issue by niemyjski** [Valian/docker-nginx-auto-ssl#27]
It might be nice for dev purposes to do a temp redirect instead of a perm redirect in case you mess something up locally.

**Comment by Valian** [comment]
Hi @niemyjski. During development, you can use the option `FORCE_HTTPS=false` and just manually select if you want to go to http or https in URL. Do you think it's enough?

**Comment by niemyjski** [comment]
I logged this because I would want to be as real as production as possible
so I want the redirect, I just don't want my browser caching that to the
end of time because it makes it almost impossible to test that route or
behavior again.
Thanks
-Blake Niemyjski

**Comment by Valian** [comment]
@niemyjski I understand. If you could prepare PR I would gladly add this feature.
