### ISSUE TITLE
Can not retrieve terms of service from certificate authority

### ISSUE THREAD

**Issue by stieuquy** [Valian/docker-nginx-auto-ssl#29]
Hi everybody,

I got error to generate certs
![Screen Shot 2019-09-25 at 20 15 45](https://user-images.githubusercontent.com/2520116/65604383-93107900-dfd1-11e9-939e-be80c11b401f.jpg)

Has anyone got this error before?
My docker-compose is same as the sample in your document.

Thanks for help!

**Comment by Java-xin** [comment]
Me too, I want to know how to solve it. @stieuquy @Valian

**Comment by otolab** [comment]
refs:
https://github.com/GUI/lua-resty-auto-ssl/issues/192

patch:
ce7b7d1a9835ff42f3a0422a88360e83210d2710

try it.

**Comment by Java-xin** [comment]
@otolab thank you Solved my problem

**Comment by ezbik** [comment]
Actually new Dehydrated must be included, which is already part of `lua-resty-auto-ssl` 
https://github.com/GUI/lua-resty-auto-ssl/issues/192

**Comment by Valian** [comment]
I will look at this and update the image soon, when I'll find some spare time. Sorry for delay!

**Comment by elertan** [comment]
> 
> 
> I will look at this and update the image soon, when I'll find some spare time. Sorry for delay!

Any idea when this will get fixed? @Valian

**Comment by shivekkhurana** [comment]
Hi @Valian,
This is a wonderful container and it has helped me to setup multiple proxies without having to know about configuring ngixn or letsencrypt. 

I had an immediate requirement to setup https on reverse proxies, and had to go with a different solution. I tried building the Docker image myself from the patch commented above, but still ran into errors. 

For anyone else who is a DevOps noob like myself, I found that configuring Traefik Reverse Proxy was really easy. It has support for Letsencrpyt (not as seemless as this image but not very hard either).  This is the blog post I referred to for setting Traefik up : https://timonweb.com/tutorials/an-example-of-docker-compose-and-traefik-config-domain-name-ssl-certificate/

I like this package more and am patiently waiting for you to rebuild this image. 

Thanks

**Comment by Valian** [comment]
@stieuquy @shivekkhurana @elertan I've updated lua-resty-auto-ssl package version in #31 and tested it on some of my websites. I think it should be fixed now, but please confirm. Also, I've started to properly tag image releases, this has tag **1.0.0** because this image seems to be already pretty stable. 

So, to test everything, try to use either tag `latest` or `1.0.0` from DockerHub. Sorry for the delay!

**Comment by shivekkhurana** [comment]
Thanks @Valian. I tested `1.0.0` and it works like a charm again :)
