### ISSUE TITLE
How to setup HTTP/S proxy to access Internet

### ISSUE THREAD

**Issue by dzieciou** [Valian/docker-nginx-auto-ssl#3]
I have have two Ubuntu machines:

* A with access to B, but without access to Internet
* B with with access to Internet

I provide access to Internet on machine A I would like to setup HTTP/HTTPS proxy on machine B and configure curl and apt-get to use this proxy.

On B I have set up nginx from docker image as follows:

    docker run -d \
      --name nginx-auto-ssl \
      --restart on-failure \
      -p 80:80 \
      -p 443:443 \
      -e ALLOWED_DOMAINS=* \
      -e FORCE_HTTPS=false \
      valian/docker-nginx-auto-ssl

 On A I set proxies

     export http_proxy=http://machine.b.com:80/
     export https_proxy=https://machine.b.com:443/

However, when I request Internet resource from A, I get information proxy is not configured:

    curl http://www.facebook.com/ -v
    * Hostname was NOT found in DNS cache
    *   Trying 172.25.10.202...
    * Connected to machine.b.com (172.x.x.x) port 80 (#0)
    > GET http://www.facebook.com/ HTTP/1.1
    > User-Agent: curl/7.35.0
    > Host: www.facebook.com
    > Accept: */*
    > Proxy-Connection: Keep-Alive
    >
    < HTTP/1.1 200 OK
    * Server openresty/1.13.6.1 is not blacklisted
    < Server: openresty/1.13.6.1
    < Date: Tue, 29 May 2018 12:52:38 GMT
    < Content-Type: text/html
    < Content-Length: 562
    < Last-Modified: Fri, 20 Apr 2018 14:42:38 GMT
    < Connection: keep-alive
    < ETag: "5ad9fc5e-232"
    < Accept-Ranges: bytes
    <
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to OpenResty!</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>Welcome to OpenResty!</h1>
    <p>If you see this page, the OpenResty web platform is successfully installed and
    working. Further configuration is required.</p>
    
    <p>For online documentation and support please refer to
    <a href="https://openresty.org/">openresty.org</a>.<br/></p>
    
    <p><em>Thank you for flying OpenResty.</em></p>
    </body>
    </html>

**Comment by Valian** [comment]
Hi @dzieciou 

I think you're looking for SOCKS proxy or tunneling. You can find many tutorials on the Internet. 

This project won't help you, because it's made for easily adding SSL certificate for your webserver, not for proxying your whole traffic through another computer.
