### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by michealjroberts** [Valian/docker-nginx-auto-ssl#38]
This isn't an issue per se, I was just wondering what the exact method is for increasing the timeout for the nginx server?

**Comment by Valian** [comment]
It's [NGINX-specific](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout), not really related to this repository. Read NGINX documentation and use one of the ways of extending this image described in README.
