### ISSUE TITLE
Include storage_adapter option

### ISSUE THREAD

**Issue by sebastianmacarescu** [Valian/docker-nginx-auto-ssl#43]
It would be great if we could configure the storage_adapter through env vars to use redis and not local file

**Comment by Valian** [comment]
Hi @sebastianmacarescu! Yes, I agree. Right now I'm rather busy with my personal life, but I would gladly accept help with that feature. Are you interested?

**Comment by sebastianmacarescu** [comment]
Hi @Valian . I've added  #44 to enable redis storage. The solution was tested on an ECS cluster with AWS ElastiCache Redis instance.
