### ISSUE TITLE
Auto renew

### ISSUE THREAD

**Issue by farfush** [Valian/docker-nginx-auto-ssl#5]
Hi, @Valian!

Any plans / ideas to add auto renew for ssl certs?

Thanks!

**Comment by fritzhealy** [comment]
I think according to the used dependency (lua-resty-auto-ssl) 

> On the fly (and free) SSL registration and renewal inside OpenResty/nginx with Let's Encrypt.

So I think this is supported out of the box?

**Comment by Valian** [comment]
Yes, it's supported out of the box :) I'm using this image every time I need an HTTPS cert and I've never had to renew anything, so I can confirm it's working :+1:

**Comment by vblagoje** [comment]
@Valian my subdomain listed in SITES didn't get renewed and expired a few days ago. I've repeatedly successfully initiated the creation of certificates using docker-nginx-auto-ssl in docker-compose setup. Perhaps I can provide the details privately and using the diagnostic response from https://check-your-website.server-daten.de/ for the site. I am using the latest image upload to Docker yesterday.

**Comment by Valian** [comment]
@vblagoje Could you anonymize and post here the first 20 lines of logs from your container (try to access your website to generate some), and also anonymized docker-compose how you're starting this image?

**Comment by vblagoje** [comment]
@Valian it seems like it was a false alarm. Even though the certificate expired it got renewed today, five days after it expired. I'll watch out for future potential cases of missed renewal. Thanks for all the great work!

**Comment by Valian** [comment]
Great :) hope everything will be working correctly.
