### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by pietru2004** [Valian/docker-nginx-auto-ssl#62]
EN:
After using the container I get ERR_CERT_AUTHORITY_INVALID is there way to fix it?

PL:
Po użyciu kontenera dostaje błąd ERR_CERT_AUTHORITY_INVALID, czy da się jakoś to naprawić?

**Comment by Valian** [comment]
Could you provide both logs from the container and start configuration? That error usually means that generation was not successful and container is using a fallback, self-generated certificate.

**Comment by pietru2004** [comment]
Long story short it is school project... 
Also the container running docker-nginx-auto-ssl image didn't give any log - checked with docker log -t container name

docker compose config section
`
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'subdomain1.domain.edu.pl;subdomain2.domain.edu.pl'
      SITES: 'subdomain1.domain.edu.pl=app:3000;subdomain2.domain.edu.pl=db:8090'
      FORCE_HTTPS: true
    depends_on:
      - app
`
Also subdomain1.domain and subdomain2.domain are replacements for actual domains(just so nobody tries to DDoS my school)
Also I checked and it gives `CN=sni-support-required-for-valid-ssl` and from what I checked it has place in fallback certgenerates

**Note:**
Also the SSL was done finaly with not dockerized nginx and certbot cause container did not work and I needed to make it work.
non the less I still want to use this image for personal website for auto SSL so...

**Comment by Valian** [comment]
Sorry for a late reply!

Just for reference - I think in your case `ALLOWED_DOMAINS` was wrong. It should be a regex, like `(subdomain1|subdomain2).domain.edu.pl`, not a semicolon-separated list. Your current value couldn't work.

**Comment by pietru2004** [comment]
I found nginx proxy manager and think it will work, also at school project we just used certbot and not conterized nginx
